version: '3'
services:
  adonis-app:
    container_name: adonis_app_management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9229:9229
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=task_management

  mysql:
    container_name: adonis_app_mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=task_management
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: adonis_app_phpmyadmin
    image: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=adonis_app_mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
