export const ErrorCode = {
  0: 'SUCCESS',
  1000: 'ERROR_SYSTEM',
  401: 'UNAUTHORIZED_ACCESS',
  403: 'FORBIDDEN',
  422: 'UNPROCESSABLE_ENTITY',

  10: 'USER_NOT_FOUND',
  11: 'USER_NOT_ACTIVE',

  30: 'TASK_NOT_FOUND',
  31: 'TASK_DELETED',
  32: 'USER_ASSIGN_TO_TASK_NOT_EXIST',

  40: 'CONVERSATION_NOT_FOUND',
  41: 'CONVERSATION_DELETED',
  42: 'CONVERSATION_CREATE_FAILED',

  50: 'BOOKING_NOT_FOUND',
  51: 'BOOKING_DELETED',
  52: 'BOOKING_CREATE_FAILED',
  53: 'BOOKING_UPDATE_FAILED',

  60: 'ROOM_NOT_FOUND',
  61: 'BOOKING_DELETED',
  62: 'BOOKING_CREATE_FAILED',
  63: 'BOOKING_UPDATE_FAILED',
}
